/**
 * 组件内文案字典。
 *
 * 刻意不走 lib/i18n 的 I18nKey 体系：那套要求 10 个 locale 文件同时存在同一批
 * key，而这个面板是新增功能、文案还在动。用局部字典先把功能跑通，等文案稳定
 * 后再一次性提升成正式 i18n key。
 */
const TEXT = {
  'zh-CN': {
    projects: '项目',
    newProject: '新建项目',
    newProjectHint: '不依赖任何文件夹，纯虚拟目录',
    emptyTitle: '还没有项目',
    emptyBody: '新建一个项目，把相关的 Markdown 整理到一起。',
    projectNamePrompt: '项目名称',
    renamePrompt: '重命名',
    folderNamePrompt: '目录名称',
    fileNamePrompt: '文件名称',
    createFolder: '创建子目录',
    createFile: '创建子文件',
    addExisting: '添加已有文件',
    rename: '重命名',
    pin: '同级置顶',
    unpin: '取消置顶',
    dragMode: '拖拽模式',
    dragModeOn: '退出拖拽模式',
    remove: '删除',
    removeConfirm: '删除「{name}」？其下所有内容一起删除。',
    removeProjectConfirm: '删除项目「{name}」？项目内的索引都会移除（实体文件不受影响）。',
    cancel: '取消',
    confirm: '确定',
    depthLimit: '最多嵌套两层目录',
    dragHint: '拖拽模式：长按节点拖到目标位置',
    dragTarget: '放到这里',
    dragIllegal: '不能放到这里',
    dragSelf: '不能拖到自己身上',
    dragIntoFile: '不能放到文件上，请放到目录或空白处',
    dragDescendant: '不能拖进自己的子目录',
    dragTooDeep: '会超过两层嵌套',
    dragNotFound: '节点不存在',
    fileCount: '个文件',
    nodeCount: '项',
    indexed: '已索引',
    private: '私有副本',
    created: '新建',
    permissionLost: '此文件的授权已失效，请重新添加',
    pickFailed: '没能添加这个文件',
    noPicker: '此设备没有可用的文件选择器',
    moveDone: '已移动',
    dropHere: '拖到这里',
    exportProject: '导出为 zip',
    importProject: '导入项目',
    exportDone: '已导出：{name}',
    exportFailed: '导出失败',
    importDone: '已导入「{name}」',
    importFailed: '导入失败，文件可能不是本应用导出的归档',
    importInvalidArchive: '这个压缩包不是本应用的项目归档，无法导入',
    archiveUnavailable: '此设备不支持归档导出',
    exportingWait: '正在导出…',
    importingWait: '正在导入…',
    bindingWait: '正在扫描目录…',
    bindTree: '绑定实体目录',
    refreshTree: '刷新（同步硬盘）',
    unbindTree: '解除绑定',
    boundBadge: '已绑定',
    bindDone: '已绑定「{name}」，共 {count} 个文件',
    bindEmpty: '该目录里没有可显示的文件',
    refreshDone: '已刷新：{count} 个文件',
    refreshFailed: '刷新失败，可能授权已失效',
    unbindDone: '已解除绑定，项目树保留为普通项目',
    unbindConfirm: '解除与「{name}」的绑定？项目树会保留，但不再跟随硬盘变化。',
    bindFailed: '绑定失败，请重新选择目录',
     writeDone: '已写入硬盘：{name}',
     writeFailed: '写回硬盘失败，改动已回滚',
     writeDenied: '此目录为只读，无法修改',
     // 拖拽移动失败的具体原因（原生按错误码回传，UI 择一展示）。
     moveFailUnknown: '没能移动：这个位置不支持移动，或源/目标不可写',
     moveFailPermission: '没能移动：绑定目录的写入权限已失效，请重新授权',
     moveFailSourceUnreadable: '没能移动：读不到「{name}」，它可能已被删除或被系统收回权限',
     moveFailSourceTooLarge: '没能移动：「{name}」太大（超过 8 MB），无法通过复制方式搬迁',
     moveFailNameConflict: '没能移动：目标目录里已经有一个叫「{name}」的同名项',
     moveFailTargetCreate: '没能移动：目标目录拒绝新建文件，它可能是只读的或不允许写入',
     moveFailTargetWrite: '没能移动：内容写不进目标目录，可能是空间不足或目标只读',
     moveFailSourceDelete: '没能移动：副本已复制，但删不掉源文件「{name}」',
     moveFailChild: '没能移动：目录「{name}」里有子项搬不动，已中止',
     moveFailNative: '没能移动：系统原生移动失败，且改用复制方式也没成功',
    reauthorize: '重新授权',
    reauthorizeWait: '请在系统弹框里选择「{name}」并允许修改…',
    reauthorizeDone: '已获得写权限，现在可以修改了',
    reauthorizeRebound: '已重新绑定「{name}」',
    reauthorizeStillReadOnly: '该目录仍不可写，可能是只读挂载或网盘只读',
    reauthorizeFailed: '重新授权失败，请重试',
    share: '分享',
    sharingWait: '正在准备分享…',
    shareDone: '已打开分享面板',
    shareFailed: '分享失败',
  },
  en: {
    projects: 'Projects',
    newProject: 'New project',
    newProjectHint: 'Pure virtual tree, no folder needed',
    emptyTitle: 'No projects yet',
    emptyBody: 'Create a project to group related Markdown files.',
    projectNamePrompt: 'Project name',
    renamePrompt: 'Rename',
    folderNamePrompt: 'Folder name',
    fileNamePrompt: 'File name',
    createFolder: 'New subfolder',
    createFile: 'New file',
    addExisting: 'Add existing file',
    rename: 'Rename',
    pin: 'Pin on top',
    unpin: 'Unpin',
    dragMode: 'Drag mode',
    dragModeOn: 'Exit drag mode',
    remove: 'Delete',
    removeConfirm: 'Delete “{name}”? Everything under it goes too.',
    removeProjectConfirm: 'Delete project “{name}”? Its index entries are removed (your originals are kept).',
    cancel: 'Cancel',
    confirm: 'OK',
    depthLimit: 'At most two nested levels',
    dragHint: 'Drag mode: long-press a node to move it',
    dragTarget: 'Drop here',
    dragIllegal: 'Cannot drop here',
    dragSelf: 'Cannot drop onto itself',
    dragIntoFile: 'Cannot drop onto a file; drop into a folder or empty space',
    dragDescendant: 'Cannot drop into its own subtree',
    dragTooDeep: 'Would exceed two levels',
    dragNotFound: 'Node not found',
    fileCount: 'files',
    nodeCount: 'items',
    indexed: 'Indexed',
    private: 'Private copy',
    created: 'New',
    permissionLost: 'Access to this file was revoked; add it again',
    pickFailed: 'Could not add this file',
    noPicker: 'No file picker available on this device',
    moveDone: 'Moved',
    dropHere: 'Drop here',
    exportProject: 'Export as zip',
    importProject: 'Import project',
    exportDone: 'Exported: {name}',
    exportFailed: 'Export failed',
    importDone: 'Imported “{name}”',
    importFailed: 'Import failed — the file may not be an archive from this app',
    importInvalidArchive: 'This zip is not a project archive from this app',
    archiveUnavailable: 'Archive export is not supported on this device',
    exportingWait: 'Exporting…',
    importingWait: 'Importing…',
    bindingWait: 'Scanning folder…',
    bindTree: 'Bind a folder',
    refreshTree: 'Refresh (sync disk)',
    unbindTree: 'Unbind',
    boundBadge: 'Bound',
    bindDone: 'Bound “{name}” — {count} files',
    bindEmpty: 'No displayable files in this folder',
    refreshDone: 'Refreshed: {count} files',
    refreshFailed: 'Refresh failed — access may have expired',
    unbindDone: 'Unbound; the tree stays as a plain project',
    unbindConfirm: 'Unbind “{name}”? The tree is kept but stops following the disk.',
    bindFailed: 'Binding failed; pick the folder again',
writeDone: 'Written to disk: {name}',
     writeFailed: 'Writing to disk failed; change rolled back',
     writeDenied: 'This folder is read-only',
     // Why a drag/move failed (native returns a specific code; the UI picks one).
     moveFailUnknown: 'Could not move: this location does not support moving, or the source/target is not writable',
     moveFailPermission: 'Could not move: write access to the bound folder has expired — re-authorize',
     moveFailSourceUnreadable: 'Could not move: cannot read “{name}” — it may be gone or access was revoked',
     moveFailSourceTooLarge: 'Could not move: “{name}” is too large (over 8 MB) to move by copying',
     moveFailNameConflict: 'Could not move: the target folder already has an item named “{name}”',
     moveFailTargetCreate: 'Could not move: the target folder refused to create a file — it may be read-only',
     moveFailTargetWrite: 'Could not move: content could not be written to the target — out of space or read-only',
     moveFailSourceDelete: 'Could not move: the copy was made, but the source “{name}” could not be deleted',
     moveFailChild: 'Could not move: a child inside “{name}” could not be moved; aborted',
     moveFailNative: 'Could not move: the system move failed and the copy fallback also failed',
    reauthorize: 'Re-authorize',
    reauthorizeWait: 'Pick “{name}” in the system dialog and allow editing…',
    reauthorizeDone: 'Write access granted — you can edit now',
    reauthorizeRebound: 'Re-bound to “{name}”',
    reauthorizeStillReadOnly: 'This folder is still read-only (read-only mount or online drive)',
    reauthorizeFailed: 'Re-authorization failed; please try again',
    share: 'Share',
    sharingWait: 'Preparing to share…',
    shareDone: 'Share sheet opened',
    shareFailed: 'Sharing failed',
  },
} as const

export type ProjectTreeLocale = keyof typeof TEXT

/** 文案表两套语言键集一致、值不同，返回类型取「键到字符串」的映射，
 *  而不是某一套语言的 as-const 字面量类型（那样另一种语言必然不匹配）。 */
export type ProjectTreeText = Record<keyof (typeof TEXT)['zh-CN'], string>

export function projectTreeText(locale: string): ProjectTreeText {
  return locale.toLowerCase().startsWith('zh') ? TEXT['zh-CN'] : TEXT.en
}
